name: Container Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/\${{ github.repository_owner }}/netguard:latest .
      - name: Push image
        run: docker push ghcr.io/\${{ github.repository_owner }}/netguard:latest
