name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Prepare project
        run: |
          flutter pub get
          flutter create . --platforms android,ios,linux,macos,windows,web
      - name: Build release artifacts
        run: ./scripts/build.sh
      - name: Package artifacts
        run: |
          tar -czf build/web.tar.gz -C build/web .
          tar -czf build/linux.tar.gz -C build/linux . || true
          tar -czf build/windows.tar.gz -C build/windows . || true
          tar -czf build/macos.tar.gz -C build/macos . || true
      - name: Generate release notes
        run: |
          VERSION="\${GITHUB_REF##*/v}"
          ./scripts/release_notes.sh "\${VERSION}" RELEASE_NOTES.md
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/web.tar.gz
            build/linux.tar.gz
            build/windows.tar.gz
            build/macos.tar.gz
